# Generated by Django 5.1.4 on 2024-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('earliest_date', models.DateField()),
                ('full_address', models.TextField()),
                ('open_from', models.TimeField()),
                ('closes_at', models.TimeField()),
                ('center_calendar_id', models.CharField(max_length=255)),
            ],
        ),
    ]
