# Generated by Django 5.1.4 on 2024-12-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='parking',
        ),
    ]
